display-prefixes-chat: true
display-prefixes-tab: true
chat-format: "[%prefixes%] &f%player%: &7%message%"

database:
  host: "localhost"
  port: 3306
  name: "ffa_db"
  user: "root"
  password: ""

arenas:
  standard:
    center-x: 0.5
    center-z: 0.5
    y-level: 0.0
    spawn-radius: 15
  speed:
    center-x: 0.5
    center-z: 381.5
    y-level: 0.0
    spawn-radius: 15
  beast:
    center-x: 0.5
    center-z: -380.5
    y-level: 0.0
    spawn-radius: 15

combat:
  timer: 20
  protection-seconds: 3.00
  ban-time-minutes: 30

leveling:
  base-xp: 100
  multiplier: 1.5